spring.application.name=backendSpringAi

# Chat
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

# Embeddings
spring.ai.model.embedding=google-genai
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

logging.level.org.springframework.ai=DEBUG