spring.application.name=backendSpringAi

spring.ai.model.chat=google-genai

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

logging.level.org.springframework.ai=DEBUG