spring.application.name=backendSpringAi

#JWT Generation | 86400000 milliseconds = 24 hours
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chat
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

# Embeddings
spring.ai.model.embedding=google-genai
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

# RAG
rag.pdf.path=documents/SQL_Complete_Notes.pdf

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai_rag
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Let Spring AI create the vector table
spring.ai.vectorstore.pgvector.initialize-schema=true

#Gemini Embeddings: 3072 dimensions
#HNSW: limited to 2000 dimensions in pgvector
#Solution: use exact search (NONE) for now, or choose a different index/model strategy later.
spring.ai.vectorstore.pgvector.index-type=NONE

logging.level.org.springframework.ai=DEBUG